version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "ladybluenotes"
    group:
      minor-patch:
        applies-to:
          -
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
