version = 1

[merge]
automerge_label = "automerge"
delete_branch_on_merge = true
merge_method = "squash"

[merge.message]
title= "pull_request_title"
include_pull_request_author = true
include_coauthors = true
include_pr_number= true
include_pull_request_url = true
body = "pull_request_body"

# once we have Renovate and CI checks
# [merge.automerge_dependencies]
# versions = ["minor", "patch"]
# usernames = ["renovate"]

[update]
# ignored_usernames = ["renovate"]
require_automerge_label = false
always = true
