minimumReleaseAge: 10080 # 1 week
minimumReleaseAgeExclude:
  - "solid-js"
  - "@solidjs/*"
  - "@kobalte/solidbase"
  - "vite"
  - "@solidjs/router"
packages:
  - "."
  - "osmium"

catalog:
  "@kobalte/solidbase": ^0.6.7

allowBuilds:
  esbuild: true

overrides:
  "@solidjs/router": "^0.16.1"
