---
title: "children"
category: "Components & Context"
use_cases: "components & context api, children usage"
tags:
  - "children"
  - "components"
  - "context"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Resolves a `children` accessor and exposes the result as an accessor with a `.toArray()` helper."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/solid/src/client/core.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Resolves a `children` accessor and exposes the result as an accessor with
a `.toArray()` helper. Use this when a component needs to inspect or
iterate over its children rather than only render them through.

## Import

```ts
import { children } from "solid-js";
```

## Type signature

```ts
function children(fn: Accessor<JSX.Element>): ChildrenReturn;
```

## Parameters

### `fn`

- **Type:** `Accessor<JSX.Element>`

Accessor for the raw children, usually `() => props.children`.

## Return value

An accessor of the resolved children, with `.toArray()` for iteration

## Examples

```tsx
function List(props: { children: Element }) {
  const items = children(() => props.children);
  return <ul>{items.toArray().map(item => <li>{item}</li>)}</ul>;
}
```

## Caveats

- Call it once in the component body and read the result. Calling `props.children` in several places creates the children several times.
- The accessor resolves lazily; the first read happens where the result is inserted or `toArray()` is called.

## Common problems

- [A child does not update when the parent's signal changes](/concepts/components-and-jsx#a-child-does-not-update-when-the-parents-signal-changes)

## Learn more

- [Children and composition](/concepts/components-and-jsx#children-and-composition)
- [Components and JSX](/concepts/components-and-jsx)

## Related types

### `ChildrenReturn`

```ts
type ChildrenReturn = Accessor<ResolvedChildren> & { toArray: () => ResolvedElement[] };
```

### `ResolvedChildren`

```ts
type ResolvedChildren = ResolvedElement | ResolvedElement[];
```
