---
title: "attribution / costs / feedback / formatOrigin / formatRerun / subscriptions / why"
category: "Advanced / Diagnostics & Dev Hooks"
use_cases: "advanced diagnostics & dev hooks api, attribution usage"
tags:
  - "attribution"
  - "costs"
  - "feedback"
  - "format"
  - "origin"
  - "rerun"
  - "subscriptions"
  - "why"
  - "advanced"
  - "diagnostics"
  - "dev"
  - "hooks"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "The attribution engine from `solid-js/attribution`: install it with `enable()`, read the interaction, navigation, hold, and re-run records it settles through `subscribe()`, and fold them with `costs()`, `feedback()`, `why()`, and `subscriptions()`."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/signals/src/core/attribution.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

The attribution engine from `solid-js/attribution`: install it with `enable()`, read the interaction, navigation, hold, and re-run records it settles through `subscribe()`, and fold them with `costs()`, `feedback()`, `why()`, and `subscriptions()`. Inert in a production build.

## Import

```ts
import { attribution, costs, feedback, formatOrigin, formatRerun, subscriptions, why } from "solid-js/attribution";
```

## `attribution`

### Type signature

```ts
const attribution: Attribution;
```

## `costs`

Aggregated cost tables since `enable()`: `scopes` ranked by self-time
(with `wastedMs` = time spent on unchanged-value runs), `writes` ranked by
total downstream re-run time each root write caused.

### Type signature

```ts
function costs(): AttributionCostTables;
```

## `feedback`

What the user waited on, folded from holds and the interaction on each
re-run: `sources` ranks async sources by the silent time writes spent held
behind them (with which affordances answered, how often, and which
interactions were held); `interactions` ranks user events by the total time
they cost — re-run work caused (long-flush hazard) beside time held
(silent-hold hazard). Facts at every duration; SILENT_HOLD is the
thresholded verdict. Three more tables round out the picture: `navigations`
ranks routes by the time spent held navigating to them (folded from settled
navigations), `flights` counts each async source's flights and how many
were abandoned before landing (the re-ask storm), and `fallbacks` measures
how long each loading boundary showed its fallback and how often that was a
flash.

### Type signature

```ts
function feedback(): AttributionFeedbackTables;
```

## `formatOrigin`

`click on button#next "Next →"`, `effect "syncTitle"`, `action "save"`, `navigation to /users/:id`, …

### Type signature

```ts
function formatOrigin(origin: ChangeOrigin): string;
```

### Parameters

#### `origin`

- **Type:** `ChangeOrigin`

## `formatRerun`

formatRerun API reference.

### Type signature

```ts
function formatRerun(event: RerunEvent): string;
```

### Parameters

#### `event`

- **Type:** `RerunEvent`

## `subscriptions`

Current dependency names of one scope — the devtools subscription view.

### Type signature

```ts
function subscriptions(target: unknown): string[];
```

### Parameters

#### `target`

- **Type:** `unknown`

## `why`

Re-run history for one node — pass a memo/effect accessor or raw node.

### Type signature

```ts
function why(target: unknown): RerunEvent[];
```

### Parameters

#### `target`

- **Type:** `unknown`

## Learn more

- [Something updates too often](/guides/debugging-reactivity#something-updates-too-often)
- [What each interaction cost](/guides/observability#what-each-interaction-cost)
- [Build an observability adapter](/guides/observability-adapters)
- [Performance](/guides/performance)
- [The screen looks dead after a click](/guides/debugging-reactivity#the-screen-looks-dead-after-a-click)
- [Debugging reactivity](/guides/debugging-reactivity)

## Related types

### `Acknowledgement`

One way the screen acknowledged a hold. `reader` is where it was painted —
the owner path of the first effect the census found reading the
affordance (`["<App>", "<Feed>", "effect"]`), so a consumer can say WHICH
screen answered, not only that one did. Absent when the affordance was
registered but the census found no reader through the graph (an optimistic
store: its readers are proxy traps, not nodes). `feedback()` ranks
acknowledgements by `kind:source` (`isPending:posts`).

```ts
interface Acknowledgement {
  kind: "isPending" | "latest" | "optimistic" | "affects";
  source: string;
  reader?: string[];
};
```

#### `kind`

- **Type:** `"isPending" | "latest" | "optimistic" | "affects"`

#### `source`

- **Type:** `string`

The node the affordance hangs on — the async source for `isPending`/`latest`, the optimistic/affected node otherwise.

#### `reader`

- **Type:** `string[]`

### `Attribution`

The engine: turn it on, subscribe to its records, read its ring buffers.
The folds over those records — `costs()`, `feedback()` — and the point
queries — `why()`, `subscriptions()` — and the formatters —
`formatRerun()`, `formatOrigin()` — are named exports of
`@solidjs/signals/attribution` rather than methods here, so a consumer
that only wants records (a production adapter) does not ship the tables a
console or an agent reads; importing a fold is what turns its accounting
on.

```ts
interface Attribution {
  enable(opts?: AttributionOptions): void;
  disable(): void;
  subscribe(listener: (event: RerunEvent) => void): () => void;
  subscribe<K extends AttributionRecordType>(
    type: K,
    listener: (record: AttributionRecords[K]) => void
  ): () => void;
  history(): readonly RerunEvent[];
  waterfalls(): readonly WaterfallRecord[];
  holds(): readonly HoldEvent[];
  navigations(): readonly NavigationEvent[];
  interactions(): readonly InteractionEvent[];
  markFlight(flight: object, startedAt?: number): void;
};
```

#### `enable`

- **Type:** `void`

#### `disable`

- **Type:** `void`

#### `subscribe`

- **Type:** `() => void`

Deliver records as they complete — see `AttributionRecords`. The bare
form is `subscribe("rerun", …)`. Records are the same objects the ring
buffers hold (`history()`, `interactions()`, `holds()`, `navigations()`),
delivered synchronously from the engine, so a listener must not write
signals. All subscriptions are dropped by `disable()`.

#### `subscribe`

- **Type:** `() => void`

#### `history`

- **Type:** `readonly RerunEvent[]`

#### `waterfalls`

- **Type:** `readonly WaterfallRecord[]`

Every graph-provable sequential flight chain observed since enable()
(ring-buffered like history()). Facts, not verdicts: chains are recorded
regardless of the duration gate — the ASYNC_WATERFALL diagnostic is the
thresholded view of the same data.

#### `holds`

- **Type:** `readonly HoldEvent[]`

Every settled transition hold that staged at least one root write since
enable() (ring-buffered like history()). Facts, not verdicts: recorded
regardless of duration or acknowledgment — the SILENT_HOLD diagnostic is
the thresholded, unacknowledged subset.

#### `navigations`

- **Type:** `readonly NavigationEvent[]`

Every navigation a router declared via `withOrigin` since enable()
(ring-buffered like history()), settled or not: what route, under which
interaction, how many writes, and — once its writes are through — how
long that took and how (`committed` in a plain drain, `held` behind
route data with the HoldEvent attached, or `superseded` by a later
navigation before it landed). Facts for any consumer that wants
navigation spans named by route: no router integration needed.

#### `interactions`

- **Type:** `readonly InteractionEvent[]`

Every user interaction a runtime declared via `withInteraction` since
enable() (ring-buffered like history()), settled or not: what was
dispatched, when, what it wrote, the re-runs and creations it caused,
the holds its writes waited in and the navigations it performed — and,
once all of that is through, how long the person waited (`settledMs`)
and how it ended (`idle` / `committed` / `held`). The per-dispatch
record `feedback().interactions` folds by name.

#### `markFlight`

- **Type:** `void`

Cooperative preload declaration: stamp a flight object (promise or async
iterable) with its true kickoff time BEFORE the reactive graph sees it.
A route preloader or query cache calls this on the promise it hands out
(on the WRAPPER it mints, with the original kickoff time — wrapping
defeats identity tracking otherwise); any dependent that later awaits it
is then judged against the real start — work already in the air when its
upstream landed is parallel, never a waterfall link. Callable while
attribution is disabled (marks made at navigation time must survive a
later enable()).

### `AttributionCostTables`

```ts
interface AttributionCostTables {
  scopes: ScopeCost[];
  writes: WriteCost[];
};
```

#### `scopes`

- **Type:** `ScopeCost[]`

Ranked by self-time.

#### `writes`

- **Type:** `WriteCost[]`

Ranked by the total downstream re-run time each root write caused.

### `AttributionFeedbackTables`

```ts
interface AttributionFeedbackTables {
  sources: FeedbackSource[];
  interactions: FeedbackInteraction[];
  navigations: FeedbackNavigation[];
  flights: FlightStats[];
  fallbacks: FallbackStats[];
};
```

#### `sources`

- **Type:** `FeedbackSource[]`

#### `interactions`

- **Type:** `FeedbackInteraction[]`

#### `navigations`

- **Type:** `FeedbackNavigation[]`

Routes ranked by the time spent held navigating to them, then by total settle time.

#### `flights`

- **Type:** `FlightStats[]`

Async sources ranked by abandoned flights, then by flights.

#### `fallbacks`

- **Type:** `FallbackStats[]`

Loading boundaries ranked by flashes, then by time shown.

### `AttributionHooks`

:::deep-dive[AttributionHooks members]
Observe-tier hook points for the reactive core.

Core's obligation is to call these with true facts at the moments they
happen; all attribution semantics (stamps, cause chains, timings, warnings)
live in the engine that installs them — `@solidjs/signals/attribution`, a
separate entry so an observe build that never enables it never ships it
(same pattern as the GlobalQueue._* feature slots). `attrHooks` is null
unless an engine is installed, so the disabled cost is one null check per
site, and prod builds fold every site out behind __OBSERVE__.

Important for implementers of call sites: a hook call must never sit inside
a `try` block — rollup's tryCatchDeoptimization retains functions referenced
inside `try` even behind a folded __OBSERVE__ guard, which re-couples the
engine into prod bundles (#2883 harness). Set a local flag inside the try
and call the hook after the catch.

```ts
interface AttributionHooks {
  interactionStart(ref: InteractionRef): void;
  interactionEnd(): void;
  originStart(ref: OriginRef): void;
  originEnd(): void;
  flushEnd(): void;
  recomputeStart(el: Computed<any>, create: boolean): void;
  recomputeEnd(
    el: Computed<any>,
    create: boolean,
    changed: boolean,
    optimistic: boolean,
    transition: boolean,
    held: boolean
  ): void;
  derivedChanged(el: Computed<any>): void;
  write(el: Signal<any> | Computed<any>, prev: unknown, value: unknown): void;
  refreshed(el: Computed<any>): void;
  flightStart(el: Computed<any>, flight: object): void;
  asyncStart(el: Computed<any>): void;
  asyncEnd(el: Computed<any>, prev: unknown, value: unknown, direct: boolean): void;
  effectRunStart(el: Computed<any>): void;
  effectRunEnd(el: Computed<any>): void;
  actionStepStart(it: object, name: string | undefined): void;
  actionStepEnd(it: object): void;
  holdStart(t: Transition): void;
  holdEnd(): void;
  transitionSettled(t: Transition): void;
  transitionMerged(target: Transition, outgoing: Transition): void;
  storeReplaced(
    path: string,
    isArray: boolean,
    total: number,
    unchanged: number,
    prevTotal: number,
    owner: Owner | null | undefined
  ): void;
  listChurn(
    el: Computed<any>,
    removed: unknown[],
    created: unknown[],
    newLen: number,
    keyed: boolean
  ): void;
  boundaryFallback(boundary: object, tree: Computed<any> | undefined, shown: boolean): void;
  currentOrigin(): ChangeOrigin | undefined;
};
```

**`interactionStart`** — `void`

`withInteraction` opened a user-interaction frame: root writes until the
matching `interactionEnd` were performed by the handler of `ref`. Frames
nest strictly (synchronous dispatch), so the engine keeps a stack.

**`interactionEnd`** — `void`

**`originStart`** — `void`

`withOrigin` opened a declared-origin frame: root writes until the
matching `originEnd` are the unit of work `ref` describes (a router's
navigation). Nests inside an interaction frame — a link click that
navigates — or stands alone (a redirect from an action, a programmatic
`navigate()`). Frames nest strictly, so the engine keeps a stack.

**`originEnd`** — `void`

**`flushEnd`** — `void`

A `flush()` drain finished: every batch it processed either committed
(its effects have run) or was parked in a held update (`holdStart`
fired for it). Fires once per drain, after the loop — not per batch, and
not for a `flush()` call that found nothing to do. Gives the engine the
"committed, screen updated" instant for writes no transition ever held.

**`recomputeStart`** — `void`

A recompute is starting; `el._deps` still holds the previous run's links.
Always paired with `recomputeEnd` (recompute has no early returns).

**`recomputeEnd`** — `void`

The recompute finished. `changed` = committed a changed value (false for
errored runs); `optimistic` = ran under an optimistic lane / lane-dirty
posture; `transition` = a transition was active or owns this node;
`held` = the value went to `_pendingValue` (a transition hold) rather
than committing directly — its reveal happens later on the transition's
own schedule.

**`derivedChanged`** — `void`

A non-effect computed committed a changed value during a re-run.

**`write`** — `void`

A signal write committed (value passed the equality gate).

**`refreshed`** — `void`

Refresh() invalidated this node (self-invalidation, no dep changed).

**`flightStart`** — `void`

A new async flight entered the system (`_inFlight` was assigned
during a recompute of `el`). Always fired inside the owning recompute —
both call paths (core's recompute and the projection self-registration)
run within one — so the engine can read the current frame stack to link
the flight to the change that caused it (waterfall chaining). `flight`
is the registered thenable/iterable itself: the engine keys a first-seen
origin registry on its identity, so shared and preloader-marked promises
carry their true start time instead of the moment the graph saw them.

**`asyncStart`** — `void`

An async landing is about to apply its value (before any branch).

**`asyncEnd`** — `void`

The async landing finished. `direct` = the landing applies the value
itself (lane/override paths); false = it went through setSignal, whose
own `write` hook already saw any committed change. Fired whether or not
the landing committed — call sites cannot carry that fact out of their
try blocks (see the try rule above), so the engine derives committed-ness
from the node's state against its asyncStart snapshot.

**`effectRunStart`** — `void`

An effect's imperative half (its effect callback) is about to run /
has run. Both fire outside the run's try; `effectRunEnd` fires whether
or not the callback threw. Writes between the two are the effect's.

**`effectRunEnd`** — `void`

**`actionStepStart`** — `void`

One synchronous step of an `action()` generator is about to run / has
run (`it.next()`/`it.throw()` up to the next yield). `it` is the
invocation's iterator — stable identity across its steps; `name` the
generator function's name. Writes between the two are the action's.

**`actionStepEnd`** — `void`

**`holdStart`** — `void`

A flush found `t` incomplete (transitionComplete's false verdict): its
writes stay staged and its queues are about to be parked. Fired before
this flush's lane effects (the visible acknowledgers — isPending
companions, optimistic values) run; `holdEnd` fires from the root
stashQueues call after them, so effect runs between the two are runs that
painted *during* the hold.

**`holdEnd`** — `void`

**`transitionSettled`** — `void`

`t` was judged complete (transitionComplete's true verdict, before `_done`
flips). Fired before its held writes commit, so `t._pendingNodes` still
lists what was staged.

**`transitionMerged`** — `void`

`outgoing` was folded into `target` (`outgoing._done = target`).

**`storeReplaced`** — `void`

A store setter batch replaced the container at `path` (e.g. `store.user`)
with a different one (both non-null, same array-ness, not the same
logical slot), and this is the leaf census of the new container against
the old: `total` leaves (own keys, or items) in the new one, `unchanged`
of which are the same value as before (identity, judged on unwrapped
values — object keys compared by key, array items by membership), and
`prevTotal` leaves in the old one. Containers above 64 leaves are not
announced. Fired per written key from the write channel's notify. The
engine decides whether the replacement was a spread-copy worth a
diagnostic. `owner` is the owner the store root was created under
(undefined when unrecorded): the finding is about the store, not about
whoever wrote it, so an `OBSERVE.exclude`d panel's store stays silent
however its writes arrive.

**`listChurn`** — `void`

A `mapArray` update both disposed and created rows: `removed` are the
items whose rows were disposed, `created` the items that got new rows,
`newLen` the list's new length, `keyed` whether a key function is in use
(false = identity or by-index). Fired after commit. The engine judges
whether the churn replaced equivalent records (unstable identity).

**`boundaryFallback`** — `void`

A loading boundary started (`shown` true) or stopped showing its
fallback. `boundary` is the boundary's queue (stable identity); `tree`
its bound subtree computed when already constructed — the first show can
fire while the subtree is still being built — whose owner chain names
the boundary. Fired at the source-set transitions (first pending source
registers / last one clears), not per flush.

**`currentOrigin`** — `ChangeOrigin | undefined`

The one query on the surface: the provenance a root write performed at
this moment would be stamped with — the innermost open frame (an effect
callback, an action step, a navigation), the interaction the handler
runs under, or, inside a recompute, the origin of the change that caused
it — or `undefined` when none applies (external). For a runtime that
records a fact of its own beside the engine's records — `@solidjs/web`'s
`"call"` record stamps the server-function call it is about to make —
so the fact joins the engine's interaction and navigation records by the
identity of the object returned, not by time.
:::

### `AttributionOptions`

```ts
interface AttributionOptions {
  log?: boolean;
  stacks?: boolean;
  historyLimit?: number;
  hotRuns?: { count: number; windowMs: number } | false;
  wideDeps?: number | false;
  hotTime?: { budgetMs: number; windowMs: number } | false;
  unstableMemos?: number | false;
  wideWrites?: number | false;
  waterfalls?: { minFlightMs: number } | false;
  holds?: { infoMs: number; warnMs: number } | false;
  longHolds?: { infoMs: number; warnMs: number } | false;
};
```

#### `log`

- **Type:** `boolean`

Pretty-print each re-run to the console (default true).

#### `stacks`

- **Type:** `boolean`

Capture the user stack frame of each write — slow (default false).

#### `historyLimit`

- **Type:** `number`

Ring-buffer size for `history()` (default 200).

#### `hotRuns`

- **Type:** `{ count: number; windowMs: number } | false`

Hot-scope warning: emit a diagnostic when one scope re-runs `count`
times within `windowMs` (default 120 runs / 1000ms — deliberately above
animation-frame cadence, so a legitimate rAF-driven scope at 60/s does
not cry wolf). `false` disables.

#### `wideDeps`

- **Type:** `number | false`

Wide-scope warning: emit a diagnostic when a scope's dependency count
reaches this (default 30) — the coarse-read / helper-leak signature.
Re-warns only if the count then grows by another 50%. `false` disables.

#### `hotTime`

- **Type:** `{ budgetMs: number; windowMs: number } | false`

Time-budget warning: emit a diagnostic when one scope's summed self-time
inside `windowMs` exceeds `budgetMs` (default 8ms / 1000ms — half a frame
spent in one scope). Unlike `hotRuns` this catches the few-but-expensive
scope that run counts miss. `false` disables.

#### `unstableMemos`

- **Type:** `number | false`

Unstable-output warning: emit a diagnostic when a memo commits a
referentially-new but shallowly-equivalent plain object/array on this
many consecutive runs (default 4). Such a memo's equality gate never
closes — every subscriber re-runs on every upstream change — which makes
it a fan-out amplifier that is otherwise only findable by profiling.
`false` disables.

#### `wideWrites`

- **Type:** `number | false`

Written-fan-out warning: emit a diagnostic when a committed root
invalidation (write, refresh, async landing) reaches a node with at
least this many subscribers (default 250). The lower-bar, opt-in sibling
of the always-on HUGE_FAN_OUT graph-size warning, which fires on the
same kind of write from GRAPH_SIZE_WARN_AT (2000) up; this one hands
over to it there, so a write never carries both. Once per node,
re-warning only on 2x subscriber growth. `false` disables.

#### `waterfalls`

- **Type:** `{ minFlightMs: number } | false`

Async-waterfall warning: emit a diagnostic when an async flight that
could only start after an upstream flight resolved (its recompute's
cause chain reaches the upstream's async landing, and its origin
post-dates that landing) forms a sequential chain of 2+ flights, each
of which took at least `minFlightMs` (default 50ms). The duration gate
is one safety valve for what the graph cannot see: a settled
preload/cache hit resolves fast and never warns. In-flight preloads are
absolved by origin: `markFlight()` stamps (and first-seen identity)
prove work predated the upstream landing — parallel, not sequential.
Chains of 2 emit at `info` severity, structured channel only (a
dependent fetch is sometimes intrinsic, and unmarked external preloads
are invisible); 3+ escalate to `warn` with console output. `false`
disables.

#### `holds`

- **Type:** `{ infoMs: number; warnMs: number } | false`

Silent-hold warning: emit a diagnostic when a user's writes were held
behind async work for at least `infoMs` (default 100ms — RAIL's "feels
instant" ceiling) and the screen never acknowledged the wait — no
`isPending()`/`latest()` reader downstream of the held writes or their
blockers, no optimistic value, no `affects()` mark, and no lane effect
painted while held. Below `warnMs`
(default 200ms — the INP "good" ceiling) the event is advisory
(structured channel only); at or above it the console gets the finding.
The engine measures to the commit, not the paint, so every number is a
floor on what the user saw; the thresholds sit at the strict end of the
band on purpose. Holds that staged no root write (initial loads, bare
`refresh()`) are never judged: nothing the user did went unanswered.
`false` disables hold tracking altogether (`longHolds` included).

#### `longHolds`

- **Type:** `{ infoMs: number; warnMs: number } | false`

Long-hold warning: emit a diagnostic when a hold's quiescent tail — the
time from the LAST write to join it until it committed — reached
`infoMs` (default 500ms), `warn` from `warnMs` (default 1000ms, where
RAIL says the user loses the thread). Measured from the last join so a
hold that keeps taking input (typing) is judged by each wait, not by its
lifetime. A hold this long is past what a stale screen should carry,
acknowledged or not: the honest UI is a fallback, which a `Loading`
boundary gives only when it has not revealed yet or its `on` prop
changed. Reported as LONG_HOLD when the hold was acknowledged; a silent
long hold stays one SILENT_HOLD with the boundary repair appended.
`false` disables.

### `AttributionRecords`

The records the engine delivers, by `subscribe(type, …)` name. Every one is
delivered synchronously at the moment it is complete — a re-run when its
recompute ends, an interaction / hold / navigation when it settles — so a
consumer never polls the ring buffers to learn that something finished.

```ts
interface AttributionRecords {
  rerun: RerunEvent;
  interaction: InteractionEvent;
  hold: HoldEvent;
  navigation: NavigationEvent;
};
```

#### `rerun`

- **Type:** `RerunEvent`

#### `interaction`

- **Type:** `InteractionEvent`

#### `hold`

- **Type:** `HoldEvent`

#### `navigation`

- **Type:** `NavigationEvent`

### `AttributionRecordType`

```ts
type AttributionRecordType = keyof AttributionRecords;
```

### `ChangeKind`

"Why did this run" attribution — the engine behind
`@solidjs/signals/attribution`.

The runtime already knows the full dependency set of every scope; this
module surfaces it. Every value commit stamps its node with a ChangeRecord
(a write, an async landing, a refresh() invalidation, or a derived change
whose `causes` chain back to root writes). When a computation re-executes,
the deps whose stamp is newer than the node's last run are its causes, so
each re-run can be explained as a chain down to the originating write:

  [why-run] effect "docTitle" ran (run 4)
    ← memo "userLabel" changed (#6)
      ← signal "notifications" write (#5) 2 → 3

This module is the attribution ENGINE: all semantics live here, and it is
decoupled from the core. `enable()` installs it into the core's narrow
observe-tier hook points (attribution-hooks.ts); core's only obligation is
to call those hooks with true facts. Disabled cost is one null check per
hook site; prod builds fold the sites out entirely. Nothing in the core
imports this module — it is reachable only through the package's
`./attribution` entry, so an observe build that never imports it never
ships it. The same hook surface is the intended substrate for external
consumers (devtools) — one mechanism, two front-ends.

```ts
type ChangeKind = "write" | "derived" | "async" | "refresh";
```

### `ChangeOrigin`

Provenance of a root change: the imperative frame that performed it.

- `interaction` — a user event handler (the web runtime marks dispatch via
  `withInteraction`). `name` is the event type, `target` the element hit
  (`button#next "Next →"`), `at` the dispatch time on the `performance.now()`
  clock — the base every feedback-latency number is measured from.
- `effect` — an effect callback (`name` = the effect's name; `run` = the
  compute run whose effect phase performed the write, when that run was
  recorded — so a write can be joined to the re-run that produced it).
- `action` — a step of an `action()` generator (`name` = the generator's
  name, when it has one). Writes after an `await` (not a `yield`) run in a
  bare microtask and stamp `external` — the documented escape.
- `async` — an async landing (`name` = the node whose flight landed).
- `navigation` — a router's navigation, declared via `withOrigin` around
  the location write (`name` = the matched route pattern `/users/:id`;
  `to`/`from` the concrete paths; `params` what the pattern bound; `at`
  when it was requested). The router-agnostic seam: any router that wraps
  its write gets navigations named by route in every hold, re-run and
  verdict, with no per-router knowledge anywhere in the engine.
- `external` — none of the above: timers, sockets, promise callbacks, setup.

`interaction` on a non-interaction frame is the user event the frame runs
under — an action started by a click, an effect whose run was caused by a
click's write, a landing whose flight a click started, a navigation a link
click performed. It is what lets every downstream cost be keyed by the
interaction that paid for it.

```ts
interface ChangeOrigin {
  kind: "interaction" | "effect" | "action" | "async" | "navigation" | "external";
  name?: string;
  target?: string;
  at?: number;
  interaction?: ChangeOrigin;
  run?: number;
  to?: string;
  from?: string;
  params?: Readonly<Record<string, string | undefined>>;
};
```

#### `kind`

- **Type:** `"interaction" | "effect" | "action" | "async" | "navigation" | "external"`

#### `name`

- **Type:** `string`

#### `target`

- **Type:** `string`

#### `at`

- **Type:** `number`

#### `interaction`

- **Type:** `ChangeOrigin`

#### `run`

- **Type:** `number`

`effect` only: the `RerunEvent.run` of the compute run this callback belongs to.

#### `to`

- **Type:** `string`

`navigation` only: concrete destination and departure paths, and the bound params.

#### `from`

- **Type:** `string`

#### `params`

- **Type:** `Readonly<Record<string, string | undefined>>`

### `ChangeRecord`

```ts
interface ChangeRecord {
  seq: number;
  kind: ChangeKind;
  name: string;
  prev?: string;
  value?: string;
  stack?: string[];
  causes?: ChangeRecord[];
  origin?: ChangeOrigin;
  at?: number;
};
```

#### `seq`

- **Type:** `number`

Global monotonic change sequence — orders causes across the app.

#### `kind`

- **Type:** `ChangeKind`

#### `name`

- **Type:** `string`

#### `prev`

- **Type:** `string`

Short previews of the value transition (writes only).

#### `value`

- **Type:** `string`

#### `stack`

- **Type:** `string[]`

First user frames of the triggering write's stack (opt-in).

#### `causes`

- **Type:** `ChangeRecord[]`

For derived changes: the upstream changes that produced this one.

#### `origin`

- **Type:** `ChangeOrigin`

Root changes only: who performed the write.

#### `at`

- **Type:** `number`

Root changes only: when the write was stamped (`performance.now()` clock).

### `FallbackStats`

Per loading boundary: how long, and how briefly, it showed its fallback.

```ts
interface FallbackStats {
  boundary: string;
  shows: number;
  shownMs: number;
  worstMs: number;
  flashes: number;
};
```

#### `boundary`

- **Type:** `string`

The boundary's owner path (`<App> › <Feed>`), or `boundary` when unnamed.

#### `shows`

- **Type:** `number`

Times the fallback was shown.

#### `shownMs`

- **Type:** `number`

Summed and worst fallback duration (ms) across completed shows.

#### `worstMs`

- **Type:** `number`

#### `flashes`

- **Type:** `number`

Shows shorter than the flash window (default 150ms): a spinner that
appeared and vanished — the other end of the SILENT_HOLD spectrum, too
much feedback for too little wait. A preload, a cache, or lifting the
fetch above the boundary removes the flash.

### `FeedbackInteraction`

```ts
interface FeedbackInteraction {
  interaction: string;
  dispatches: number;
  runs: number;
  selfMs: number;
  worstDispatchMs: number;
  holds: number;
  heldMs: number;
  silentMs: number;
  worstHoldMs: number;
};
```

#### `interaction`

- **Type:** `string`

`click on button#next "Next →"` — type and target; repeated dispatches fold together.

#### `dispatches`

- **Type:** `number`

Distinct dispatches seen (by dispatch time).

#### `runs`

- **Type:** `number`

Re-runs traced back to this interaction, and their summed self-time.

#### `selfMs`

- **Type:** `number`

#### `worstDispatchMs`

- **Type:** `number`

The most re-run self-time a single dispatch caused — the long-flush hazard.

#### `holds`

- **Type:** `number`

Holds this interaction's writes waited in — the silent-hold hazard.

#### `heldMs`

- **Type:** `number`

#### `silentMs`

- **Type:** `number`

#### `worstHoldMs`

- **Type:** `number`

### `FeedbackNavigation`

Per route: what navigating to it cost, folded from settled
`NavigationEvent`s — the route-level view a router integration used to
have to build itself, from the runtime's own facts.

```ts
interface FeedbackNavigation {
  name: string;
  navigations: number;
  settledMs: number;
  worstMs: number;
  held: number;
  heldMs: number;
  silent: number;
  superseded: number;
  redirected: number;
};
```

#### `name`

- **Type:** `string`

The route pattern (`/users/:id`), or the concrete `to` when the router gave no pattern.

#### `navigations`

- **Type:** `number`

#### `settledMs`

- **Type:** `number`

Summed and worst request-to-settle time (ms) across settled navigations.

#### `worstMs`

- **Type:** `number`

#### `held`

- **Type:** `number`

Navigations whose writes waited in a hold, and the time they waited.

#### `heldMs`

- **Type:** `number`

#### `silent`

- **Type:** `number`

Held navigations the screen acknowledged nothing for — the SILENT_HOLD signature.

#### `superseded`

- **Type:** `number`

Navigations overwritten by a later one before they landed.

#### `redirected`

- **Type:** `number`

Navigations a redirect sent elsewhere on the way (keyed by where they ended up).

### `FeedbackSource`

```ts
interface FeedbackSource {
  sources: string[];
  holds: number;
  heldMs: number;
  worstMs: number;
  silent: number;
  silentMs: number;
  latestOnly: number;
  long: number;
  longMs: number;
  acknowledgedBy: { by: string; holds: number }[];
  interactions: { interaction: string; holds: number }[];
  writes: string[];
  actions: number;
};
```

#### `sources`

- **Type:** `string[]`

The async nodes the holds waited on; empty when an action alone kept them open.

#### `holds`

- **Type:** `number`

#### `heldMs`

- **Type:** `number`

Summed wait across the holds (ms).

#### `worstMs`

- **Type:** `number`

#### `silent`

- **Type:** `number`

Holds with no acknowledgment at all — the SILENT_HOLD signature, at any duration.

#### `silentMs`

- **Type:** `number`

#### `latestOnly`

- **Type:** `number`

Holds whose only acknowledgment was a `latest()` shadow: the input showed, nothing said "loading".

#### `long`

- **Type:** `number`

Holds whose quiescent tail (last write to join → commit) reached
`longHolds.infoMs`, acknowledged or not — the LONG_HOLD signature at the
table level. The affordance is not the whole answer there: a fallback
(`Loading` keyed with `on`), a preload, a cache, or a faster source is.
`longMs` sums the tails.

#### `longMs`

- **Type:** `number`

#### `acknowledgedBy`

- **Type:** `{ by: string; holds: number }[]`

Which affordances answered, and in how many holds — ranked.

#### `interactions`

- **Type:** `{ interaction: string; holds: number }[]`

Interactions whose writes were held here, ranked by holds.

#### `writes`

- **Type:** `string[]`

Distinct root writes that were held.

#### `actions`

- **Type:** `number`

Holds an action opened or joined.

### `FlightLink`

One landed flight: its node name, wall duration, and upstream chain.

```ts
interface FlightLink {
  name: string;
  ms: number;
};
```

#### `name`

- **Type:** `string`

#### `ms`

- **Type:** `number`

### `FlightStats`

Per async source: how many flights it started, and how many it threw away.

```ts
interface FlightStats {
  source: string;
  flights: number;
  landed: number;
  abandoned: number;
  landedMs: number;
  worstMs: number;
};
```

#### `source`

- **Type:** `string`

#### `flights`

- **Type:** `number`

Flights registered (a recompute that produced a new promise/iterable).

#### `landed`

- **Type:** `number`

Flights that landed (whether or not the value changed).

#### `abandoned`

- **Type:** `number`

Flights superseded by a newer one before landing — the search-as-you-type
signature when large: every keystroke asked, most answers were discarded.
A debounced/equality-gated derivation between input and fetch is the repair.

#### `landedMs`

- **Type:** `number`

Summed and worst wall time of landed flights (ms).

#### `worstMs`

- **Type:** `number`

### `HeldWrite`

```ts
interface HeldWrite {
  name: string;
  prev?: string;
  value?: string;
  origin?: ChangeOrigin;
};
```

#### `name`

- **Type:** `string`

#### `prev`

- **Type:** `string`

#### `value`

- **Type:** `string`

#### `origin`

- **Type:** `ChangeOrigin`

### `HoldEvent`

```ts
interface HoldEvent {
  at: number;
  holdMs: number;
  tailMs: number;
  interaction?: ChangeOrigin;
  origin?: ChangeOrigin;
  flushes: number;
  heldWrites: HeldWrite[];
  blockers: string[];
  acknowledgements: Acknowledgement[];
  paintedDuringHold: number;
  action: boolean;
};
```

#### `at`

- **Type:** `number`

When the wait began (`performance.now()` clock): the interaction that
performed the held writes when one is known (`interaction.at`) or the
first flush that parked them, whichever is earlier. `at + holdMs` is the
commit.

#### `holdMs`

- **Type:** `number`

Wall time the user waited: `at` to the commit.

#### `tailMs`

- **Type:** `number`

The quiescent tail: from the LAST held write to join (the user's final
input) to the commit. Equal to `holdMs` for a single write; shorter when
the hold kept taking input. The LONG_HOLD measure.

#### `interaction`

- **Type:** `ChangeOrigin`

The user interaction whose writes were held, when the stamp is known.

#### `origin`

- **Type:** `ChangeOrigin`

The declared unit of work the held writes belong to — the `navigation`
a router described via `withOrigin` — when one is known. What names the
hold by route (`navigation to /users/:id`) rather than by signal; the
same object as `navigations()[].origin`, so the two join by identity.

#### `flushes`

- **Type:** `number`

Flushes that ended with the hold still open.

#### `heldWrites`

- **Type:** `HeldWrite[]`

Root signal writes staged behind the hold (the user's unanswered input).

#### `blockers`

- **Type:** `string[]`

Async nodes the hold waited on (union across its parked flushes).

#### `acknowledgements`

- **Type:** `Acknowledgement[]`

Feedback the graph provably rendered for this hold — an `isPending()`
reader, a `latest()` shadow, an optimistic value, an `affects()` mark —
one entry per affordance, in the order found. Empty and
`paintedDuringHold === 0` is the SILENT_HOLD signature.

#### `paintedDuringHold`

- **Type:** `number`

Effect callbacks that ran inside the hold's parked flushes. Mainline
effects are stashed while a hold is open, so these are lane effects —
readers of optimistic values and of `isPending()`/`latest()` companions,
i.e. the screen changing in response to the hold. An unrelated effect
cannot land here: it waits with everything else.

#### `action`

- **Type:** `boolean`

The hold was opened (or joined) by an `action()`.

### `InteractionEvent`

```ts
interface InteractionEvent {
  name: string;
  target?: string;
  at: number;
  handlerMs: number;
  writes: number;
  runs: number;
  created: number;
  runMs: number;
  holds: HoldEvent[];
  navigations: NavigationEvent[];
  settledMs?: number;
  outcome?: "idle" | "committed" | "held";
  origin: ChangeOrigin;
};
```

#### `name`

- **Type:** `string`

Event type — `click`, `keydown`, `input`…

#### `target`

- **Type:** `string`

The element hit, as the runtime described it — `button#next "Next →"`.

#### `at`

- **Type:** `number`

Dispatch time (`performance.now()` clock).

#### `handlerMs`

- **Type:** `number`

Wall time of the handler itself, dispatch to return.

#### `writes`

- **Type:** `number`

Root writes attributed to the frame: the handler's, and those of frames it opened (a navigation).

#### `runs`

- **Type:** `number`

Re-runs traced back to this interaction while the record was open.

#### `created`

- **Type:** `number`

Computations created in those runs or in the frame's flushes (the "create 1,000 rows" work).

#### `runMs`

- **Type:** `number`

Summed self-time of `runs` and `created` (ms). Quantized per run; `settledMs` is the wall clock.

#### `holds`

- **Type:** `HoldEvent[]`

Holds its writes waited in, in settle order.

#### `navigations`

- **Type:** `NavigationEvent[]`

Navigations performed under it, in open order.

#### `settledMs`

- **Type:** `number`

Dispatch to settle: the handler's return when it wrote nothing, the end of
the drain that committed its writes, or the commit of the last hold they
waited in — whichever came last. `undefined` while unsettled.

#### `outcome`

- **Type:** `"idle" | "committed" | "held"`

#### `origin`

- **Type:** `ChangeOrigin`

The frame object every downstream fact carries — `ChangeOrigin.interaction`
on writes and frames, `RerunEvent.interaction`, `HoldEvent.interaction`,
`NavigationEvent.interaction`. Join key, by identity.

### `InteractionRef`

A user interaction, as a rendering runtime describes it to `withInteraction`.

```ts
interface InteractionRef {
  type: string;
  target?: string;
  at?: number;
};
```

#### `type`

- **Type:** `string`

Event type — `click`, `keydown`, `input`…

#### `target`

- **Type:** `string`

The element hit, e.g. `button#next "Next →"`.

#### `at`

- **Type:** `number`

Dispatch time on the `performance.now()` clock; defaults to now.

### `NavigationEvent`

```ts
interface NavigationEvent {
  name?: string;
  to?: string;
  from?: string;
  params?: Readonly<Record<string, string | undefined>>;
  at: number;
  interaction?: ChangeOrigin;
  writes: number;
  redirects?: NavigationHop[];
  settledMs?: number;
  outcome?: "committed" | "held" | "superseded";
  hold?: HoldEvent;
  origin: ChangeOrigin;
};
```

#### `name`

- **Type:** `string`

The matched route pattern the router gave — `/users/:id`. After a redirect, the final one.

#### `to`

- **Type:** `string`

#### `from`

- **Type:** `string`

#### `params`

- **Type:** `Readonly<Record<string, string | undefined>>`

#### `at`

- **Type:** `number`

When the navigation was requested (`performance.now()` clock).

#### `interaction`

- **Type:** `ChangeOrigin`

The user interaction it ran under, when known — a link click.

#### `writes`

- **Type:** `number`

Root writes the frame performed, redirect hops included.

#### `redirects`

- **Type:** `NavigationHop[]`

Destinations abandoned along the way, in order — present only when a redirect occurred.

#### `settledMs`

- **Type:** `number`

Wall time from the request to settle: the end of the drain that committed
its writes, or the commit of the hold they waited in. `undefined` while
unsettled.

#### `outcome`

- **Type:** `"committed" | "held" | "superseded"`

#### `hold`

- **Type:** `HoldEvent`

The hold its writes waited in, when hold tracking recorded one.

#### `origin`

- **Type:** `ChangeOrigin`

The frame object its writes were stamped with — `ChangeRecord.origin` on
each, `HoldEvent.origin` on the hold. Join key, by identity.

### `NavigationHop`

A destination a navigation abandoned when a redirect sent it elsewhere.

```ts
interface NavigationHop {
  name?: string;
  to?: string;
  params?: Readonly<Record<string, string | undefined>>;
  at: number;
};
```

#### `name`

- **Type:** `string`

#### `to`

- **Type:** `string`

#### `params`

- **Type:** `Readonly<Record<string, string | undefined>>`

#### `at`

- **Type:** `number`

When the redirect away from it was declared (`performance.now()` clock).

### `NavigationRef`

A navigation, as a router describes it to `withOrigin` around the location
write it is about to perform. Match eagerly and describe before writing:
the engine keys the work the write causes — the hold behind route data,
the re-runs, the verdicts — to this record, and names it by the
parametrized route so occurrences fold together.

The engine keeps the object and reads `name`, `to` and `params` again when
the navigation settles (and when a hold on it is judged), so a router whose
match is not final at write time — a lazy route subtree that resolves inside
the hold — may describe coarsely (`/admin/*`) and assign the exact pattern
and params onto the same object once it knows them. `from` and `at` are
read once, when the frame opens.

```ts
interface NavigationRef {
  kind: "navigation";
  name?: string;
  to?: string;
  from?: string;
  params?: Readonly<Record<string, string | undefined>>;
  at?: number;
  redirect?: number;
};
```

#### `kind`

- **Type:** `"navigation"`

#### `name`

- **Type:** `string`

The matched route pattern — `/users/:id`. The name every consumer groups by.

#### `to`

- **Type:** `string`

Concrete destination path.

#### `from`

- **Type:** `string`

Concrete path being left.

#### `params`

- **Type:** `Readonly<Record<string, string | undefined>>`

Route params the pattern bound — `{ id: "42" }` (optional params unbound: `undefined`).

#### `at`

- **Type:** `number`

When the navigation was requested on the `performance.now()` clock;
defaults to now. A router whose request predates the write (loaders
awaited before the location moves) passes its own start here.

#### `redirect`

- **Type:** `number`

`>= 1`: this frame is the Nth redirect hop of the navigation still
pending — a guard or loader sent it elsewhere before it landed — not a
new navigation. The engine folds it onto that pending record: the record
keeps the user's request time and interaction, its destination becomes
this one, and the abandoned destination is kept in `redirects`. Without
a pending navigation to fold onto it opens a navigation of its own.

### `OriginRef`

What `withOrigin` accepts: a declared unit of work whose writes the engine
should attribute as a whole. A discriminated union so kinds can be added
(a form submission, a tab switch) without the seam changing shape; the
engine knows `navigation` today.

```ts
type OriginRef = NavigationRef;
```

### `RerunEvent`

```ts
interface RerunEvent {
  run: number;
  at: number;
  nodeRuns: number;
  nodeKind: "effect" | "memo";
  nodeName: string;
  nodeId: number;
  causes: ChangeRecord[];
  depCount: number;
  depsAdded: string[];
  depsRemoved: string[];
  selfMs: number;
  totalMs: number;
  changed: boolean;
  phase: "plain" | "held" | "optimistic";
  held: boolean;
  interaction?: ChangeOrigin;
};
```

#### `run`

- **Type:** `number`

Global monotonic run sequence.

#### `at`

- **Type:** `number`

When the run started (`performance.now()` clock).

#### `nodeRuns`

- **Type:** `number`

How many times this node has re-run since attribution was enabled.

#### `nodeKind`

- **Type:** `"effect" | "memo"`

#### `nodeName`

- **Type:** `string`

#### `nodeId`

- **Type:** `number`

Identity of the scope that ran, stable for the node's lifetime within
the process: every run of one memo/effect carries the same `nodeId`, so
runs join to a scope after the record has left the process (where
`nodeName` alone would merge every unnamed `effect`). The engine's own
per-node id, also what `ChangeOrigin.run` and the cycle/relay checks
key on; not meaningful across processes or sessions. In-process
consumers that want the live node ask `OBSERVE.subjectOf(event)`.

#### `causes`

- **Type:** `ChangeRecord[]`

The deps that changed since this node's previous run. Empty means the
re-run was not triggered by a tracked value change (creation-adjacent
pull, error retry, or a cause this prototype does not stamp yet).

#### `depCount`

- **Type:** `number`

Dependency count after this run.

#### `depsAdded`

- **Type:** `string[]`

Names of deps this run subscribed to that the previous run did not.

#### `depsRemoved`

- **Type:** `string[]`

Names of deps the previous run had that this run dropped.

#### `selfMs`

- **Type:** `number`

Wall time of this run excluding nested recomputes (ms).

#### `totalMs`

- **Type:** `number`

Wall time of this run including nested recomputes (ms).

#### `changed`

- **Type:** `boolean`

Whether the run produced a changed value. A PLAIN memo run with
`changed: false` was pure waste — the equality cutoff stopped it from
notifying anyone. Effects run with `_equals: false` in core (their
effect phase re-fires on every recompute), so the engine derives this
fact itself: an effect run whose compute output is identical to the
previous run's reports `changed: false` — the phase re-fired with the
same input, pure waste. Side-effect-only computes (`undefined` output)
are exempt: identity of `undefined` proves nothing about their work.
Summed as `wastedMs` in costs() (plain, non-held runs only — see
`phase`).

#### `phase`

- **Type:** `"plain" | "held" | "optimistic"`

Which posture this run executed under. "optimistic" = under an
optimistic lane (overlay recompute); "held" = a hold was open or owns
the node (the run may be replayed/settled later); "plain" = an ordinary
committed run. Overlay runs are real work (they count toward time
budgets) but are never blamed as waste, and costs() reports their time
separately as `overlayMs`.

#### `held`

- **Type:** `boolean`

The changed value was parked in `_pendingValue` (held) rather than
committed directly; its reveal happens on the hold's own schedule. Held
runs are excluded from waste accounting.

#### `interaction`

- **Type:** `ChangeOrigin`

The user interaction this run traces back to through its causes, if any.

### `ScopeCost`

```ts
interface ScopeCost {
  name: string;
  kind: "effect" | "memo";
  runs: number;
  selfMs: number;
  wastedMs: number;
  overlayMs: number;
};
```

#### `name`

- **Type:** `string`

#### `kind`

- **Type:** `"effect" | "memo"`

#### `runs`

- **Type:** `number`

#### `selfMs`

- **Type:** `number`

#### `wastedMs`

- **Type:** `number`

Self-time of PLAIN, non-held runs that produced an unchanged value —
the recoverable number. Overlay runs (optimistic/transition) are never
counted here: an optimistic recompute landing back on the committed
value is the mechanism working, not waste.

#### `overlayMs`

- **Type:** `number`

Self-time spent in optimistic/transition (overlay) runs.

### `WaterfallRecord`

```ts
interface WaterfallRecord {
  chain: FlightLink[];
  sequentialMs: number;
};
```

#### `chain`

- **Type:** `FlightLink[]`

Sequential flights, oldest first, ending at the flight that landed.

#### `sequentialMs`

- **Type:** `number`

Summed wall time of the chain — the serialized cost.

### `WriteCost`

```ts
interface WriteCost {
  name: string;
  runs: number;
  downstreamMs: number;
};
```

#### `name`

- **Type:** `string`

Root cause name (a signal write, async landing, or refresh target).

#### `runs`

- **Type:** `number`

Number of downstream re-runs this root triggered.

#### `downstreamMs`

- **Type:** `number`

Summed self-time of every downstream re-run it caused.
