name: "Bug Report 🪲"
description: Report an issue or possible bug with the functionality of the Solid docs website. (Not related to the content of the site.)
title: "[Bug]: "
labels: [
  "bug", 
  "pending review"
]
assignees: 
- danieljcafonso
- atilafassina

body:
  - type: textarea
    id: description
    attributes:
      label: "📝 Issue Description"
      description: Please describe the issue you are experiencing while using the Docs website.
      placeholder: Description of your observation...
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "📋 On which page(s) it occurs"
      description: Please indicate on which page(s) the issue occurs.
      placeholder: https://docs.solidjs.com/concepts/intro-to-reactivity
    validations:
        required: true
  - type: textarea
    id: expected
    attributes:
      label: "🤔 Expected Behavior"
      description: Please describe what the expected behavior should be.
      placeholder: When on this page, I expected . . . 
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: "👀 Current Behavior"
      description: Please describe what the current behavior is.
      placeholder: But instead, on this page I'm noticing . . . 
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 🖥️ Browser
      description: Indicate which browser and version you are using.
      placeholder: Chrome X
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: "📄 Additional Information"
      description: Any additional information that may be relevant for the issue.
    validations:
      required: false
