name: "Other Report 🌐"
title: "[Other]:"
description: Report something else we should know about the docs site!
labels: [
"pending review"
]
body:
  - type: textarea
    id: issue
    attributes:
      label: "📋 Explain your issue"
      description: Please describe the problem with the documentation in detail.
      placeholder: "..."
    validations:
        required: true
