name: "Request 💡"
title: "[Request]:"
description: Share an idea.
labels: [
  "request", "pending review"
]
assignees:
- ladybluenotes
body:
  - type: markdown
    attributes:
      value: "## Reminder: If reporting a minor correction (e.g. typo), feel free to submit a PR directly!"
  - type: dropdown
    id: request-topic
    attributes:
      label: "What is this request related to?"
      options: 
        - Request
        - Styling
        - Feature
    validations:
      required: true
  - type: textarea
    id: page
    attributes:
      label: "📋 Suggested"
      description: Please provide the URL of the page(s) or section this idea is related to.
      placeholder: https://docs.solidjs.com/concepts/intro-to-reactivity
    validations:
        required: false
  - type: textarea
    id: generalDesc
    attributes:
      label: "📋 General description or bullet points"
      description: Please provide a general description or bullet points about what you would like to see added.
      placeholder: "..."
    validations:
        required: true
  - type: textarea
    id: example
    attributes:
      label: "🖥️ Reproduction of code samples in StackBlitz"
      description: If you would like to suggest code samples please attach a working reproduction.
      placeholder: "..."
    validations:
        required: false
