---
title: "deep"
category: "Advanced / Store Advanced"
use_cases: "advanced store advanced api, deep usage"
tags:
  - "deep"
  - "advanced"
  - "store"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Subscribes the surrounding scope to every reachable level of a store value, then returns its plain view."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/signals/src/store/index.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Subscribes the surrounding scope to every reachable level of a store value, then returns its plain view. Use it when any change anywhere in the subtree should re-run the computation.

## Import

```ts
import { deep } from "solid-js";
```

## Type signature

```ts
function deep<T>(value: T): T;
```

## Parameters

### `value`

- **Type:** `T`

## Learn more

- [Stores](/concepts/stores)
