---
title: "isWrappable"
category: "Advanced / Store Advanced"
use_cases: "advanced store advanced api, iswrappable usage"
tags:
  - "is"
  - "wrappable"
  - "advanced"
  - "store"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Returns whether a value would be wrapped in a store proxy."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/signals/src/store/store.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Returns whether a value would be wrapped in a store proxy. Plain objects, arrays, and class instances are wrappable; built-in objects such as `Map` and `Date`, frozen objects, and primitives are not.

## Import

```ts
import { isWrappable } from "solid-js";
```

## Type signature

```ts
function isWrappable<T>(obj: T | NotWrappable): obj is T;
```

## Parameters

### `obj`

- **Type:** `T | NotWrappable`

## Learn more

- [Stores](/concepts/stores)

## Related types

### `NotWrappable`

```ts
type NotWrappable =
  | string
  | number
  | bigint
  | symbol
  | boolean
  | Function
  | null
  | undefined
  | SolidStore.Unwrappable[keyof SolidStore.Unwrappable];
```
