---
title: "snapshot"
category: "Advanced / Store Advanced"
use_cases: "advanced store advanced api, snapshot usage"
tags:
  - "snapshot"
  - "advanced"
  - "store"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Returns the plain, unwrapped view of a store value without tracking, for serialization or for passing to code that must not observe the store."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/signals/src/store/index.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Returns the plain, unwrapped view of a store value without tracking, for serialization or for passing to code that must not observe the store. Subtrees with no pending changes are returned as-is rather than copied.

## Import

```ts
import { snapshot } from "solid-js";
```

## Type signature

```ts
function snapshot<T>(value: T): T;
```

## Parameters

### `value`

- **Type:** `T`

## Learn more

- [Stores](/concepts/stores)
