---
title: "isServer"
category: "Rendering & SSR"
use_cases: "rendering & ssr api, isserver usage"
tags:
  - "is"
  - "server"
  - "rendering"
  - "ssr"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Build-time constant that is `true` in server output and `false` in browser output."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/web/src/index.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Build-time constant that is `true` in server output and `false` in browser output.

## Import

```ts
import { isServer } from "@solidjs/web";
```

## Type signature

```ts
const isServer: boolean;
```

## Examples

```ts
import { isServer } from "@solidjs/web";

if (!isServer) {
  // Browser-only: tree-shaken out of the SSR bundle.
  window.addEventListener("resize", onResize);
}
```

```ts
if (!isServer) {
	window.addEventListener("resize", onResize);
}
```

## Caveats

- It is a build-time constant. Code behind `if (!isServer)` is removed from the server bundle, so use it rather than `typeof window` checks.

## Learn more

- [Server and client boundaries](/concepts/rendering-and-ssr#server-and-client-boundaries)
- [SSR-safe code](/guides/ssr-safe-code)
- [Rendering and SSR](/concepts/rendering-and-ssr)
- [Choose a rendering mode](/guides/choose-a-rendering-mode)
