---
title: "Context / ContextProviderComponent"
category: "Types"
use_cases: "types api, context usage"
tags:
  - "context"
  - "provider"
  - "component"
  - "types"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Context API reference."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/solid/src/client/core.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Context API reference.

## Import

```ts
import type { Context, ContextProviderComponent } from "solid-js";
```

## `Context`

### Type signature

```ts
interface Context<T> extends ContextProviderComponent<T> {
  id: symbol;
  defaultValue: T | undefined;
};
```

### Properties

#### `id`

- **Type:** `symbol`

#### `defaultValue`

- **Type:** `T | undefined`

## `ContextProviderComponent`

ContextProviderComponent API reference.

### Type signature

```ts
type ContextProviderComponent<T> = FlowComponent<{ value: T }>;
```

## Learn more

- [TypeScript](/guides/typescript)
