---
title: "enableExternalSource"
category: "Advanced / Interop & Async"
use_cases: "advanced interop & async api, enableexternalsource usage"
tags:
  - "enable"
  - "external"
  - "source"
  - "advanced"
  - "interop"
  - "async"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Registers an adapter that lets Solid track reads from a non-Solid reactive system, such as MobX or Vue reactivity, inside its computations."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/signals/src/core/external.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Registers an adapter that lets Solid track reads from a non-Solid reactive system, such as MobX or Vue reactivity, inside its computations.

## Import

```ts
import { enableExternalSource } from "solid-js";
```

## Type signature

```ts
function enableExternalSource(config: ExternalSourceConfig): void;
```

## Parameters

### `config`

- **Type:** `ExternalSourceConfig`

## Learn more

- [Feed an outside source into the graph](/guides/integrate-non-solid-code#feed-an-outside-source-into-the-graph)
- [Async reactivity](/concepts/async-reactivity)
- [Integrate non-Solid code](/guides/integrate-non-solid-code)

## Related types

### `ExternalSource`

```ts
interface ExternalSource {
  track: (prev: any) => any;
  dispose: () => void;
};
```

#### `track`

- **Type:** `(prev: any) => any`

#### `dispose`

- **Type:** `() => void`

### `ExternalSourceConfig`

```ts
interface ExternalSourceConfig {
  factory: ExternalSourceFactory;
  untrack?: <T>(fn: () => T) => T;
};
```

#### `factory`

- **Type:** `ExternalSourceFactory`

#### `untrack`

- **Type:** `<T>(fn: () => T) => T`

### `ExternalSourceFactory`

```ts
type ExternalSourceFactory = (fn: (prev: any) => any, trigger: () => void) => ExternalSource;
```
