---
title: "createRoot"
category: "Advanced / Owner & Introspection"
use_cases: "advanced owner & introspection api, createroot usage"
tags:
  - "create"
  - "root"
  - "advanced"
  - "owner"
  - "introspection"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Creates a non-tracked owner scope that doesn't auto-dispose. Pass `id` to seed hydration ids for the tree it owns."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/solid/src/client/hydration.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Creates a non-tracked owner scope that doesn't auto-dispose. Pass `id`
to seed hydration ids for the tree it owns.

```ts
const dispose = createRoot(dispose => {
  // ...
  return dispose;
});
```

**Hydration:** a root created during hydration marks itself as the
snapshot scope, so writes landing during the hydration pass are held
until the pass completes (the mark used to depend on which primitive
ran first under it).

> `render()` creates the root for normal app code. Reach for `createRoot` in tests, libraries, or non-render entry points that need to host a reactive scope.

## Import

```ts
import { createRoot } from "solid-js";
```

## Type signature

```ts
function createRoot<T>(
  init: ((dispose: () => void) => T) | (() => T),
  options?: { id?: string; transparent?: boolean }
): T;
```

## Parameters

### `init`

- **Type:** `((dispose: () => void) => T) | (() => T)`

### `options`

- **Type:** `{ id?: string; transparent?: boolean }`
- Optional

## Examples

```ts
const dispose = createRoot(dispose => {
  const [n, setN] = createSignal(0);
  createEffect(() => n(), value => console.log(value));
  setInterval(() => setN(x => x + 1), 1000);
  return dispose;
});

// Later, to tear everything down:
dispose();
```

## Learn more

- [Run outside a component](/guides/custom-primitives#run-outside-a-component)
- [Ownership](/concepts/reactivity#ownership)
- [Custom primitives](/guides/custom-primitives)
