---
title: "markSafeError / isSafeError"
category: "Request & response"
use_cases: "request & response api, marksafeerror usage"
tags:
  - "mark"
  - "safe"
  - "error"
  - "is"
  - "request"
  - "response"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Marks `error` as safe to serialize to the client verbatim, opting it out of production error sanitization (see `handleServerFunctionRequest`)."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/web/src/response.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Marks `error` as safe to serialize to the client verbatim, opting it out
of production error sanitization (see `handleServerFunctionRequest`). Use
for errors whose message/properties are intentional client-facing content.
Returns the same value for convenient `throw markSafeError(new Error(...))`.

## Import

```ts
import { markSafeError, isSafeError } from "@solidjs/web";
```

## `markSafeError`

### Type signature

```ts
function markSafeError<E>(error: E): E;
```

### Parameters

#### `error`

- **Type:** `E`

### Common problems

- [`respond()` reaches the client as `Internal Server Error`](/guides/forms#respond-reaches-the-client-as-internal-server-error)

## `isSafeError`

Returns whether a value is branded as safe to serialize to a client.

### Type signature

```ts
function isSafeError(value: unknown): value is Error;
```

### Parameters

#### `value`

- **Type:** `unknown`

## Learn more

- [Arguments and security](/building-apps/server-functions/arguments-and-security)
- [Forms](/guides/forms)
- [Mutations and responses](/building-apps/server-functions/mutations-and-responses)
- [Middleware and API routes](/building-apps/middleware-and-api-routes)
