---
title: "parseServerFunctionActionUrl / serverFunctionActionUrl / serverFunctionUrl"
category: "Server functions / Integration"
use_cases: "server functions integration api, parseserverfunctionactionurl usage"
tags:
  - "parse"
  - "server"
  - "function"
  - "action"
  - "url"
  - "functions"
  - "integration"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Reads the function id back out of a server-rendered action url."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/web/server-functions/src/client.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Reads the function id back out of a server-rendered action url.

## Import

```ts
import { parseServerFunctionActionUrl, serverFunctionActionUrl, serverFunctionUrl } from "@solidjs/web/server-functions";
```

## `parseServerFunctionActionUrl`

### Type signature

```ts
function parseServerFunctionActionUrl(url: string): string | null;
```

### Parameters

#### `url`

- **Type:** `string`

## `serverFunctionActionUrl`

The plain-HTTP address of a function: `<endpoint>/<id>[?args=...]`.

### Type signature

```ts
function serverFunctionActionUrl(
  fn: ServerFunction | string,
  ...boundArgs: readonly unknown[]
): string;
```

### Parameters

#### `fn`

- **Type:** `ServerFunction | string`

#### `boundArgs`

- **Type:** `readonly unknown[]`

## `serverFunctionUrl`

Builds a server-function URL, optionally with JSON-safe bound arguments.

### Type signature

```ts
function serverFunctionUrl<A extends readonly unknown[]>(
  fn: ServerFunction<A, any>,
  ...args: A
): string;
```

### Parameters

#### `fn`

- **Type:** `ServerFunction<A, any>`

#### `args`

- **Type:** `A`
