---
title: "affects"
category: "Lifecycle & Actions"
use_cases: "lifecycle & actions api, affects usage"
tags:
  - "affects"
  - "lifecycle"
  - "actions"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Marks a reactive source or store location as pending while work that will change it is in flight."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/signals/src/affects.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Marks a reactive source or store location as pending while work that will change it is in flight. Marked values remain readable, and derived readers report the pending state until the surrounding action or update settles.

## Import

```ts
import { affects } from "solid-js";
```

## Type signature

```ts
function affects(target: Accessor<unknown> | Store<object>): void;
function affects<T extends object>(target: Store<T>, key: keyof T): void;
```

## Parameters

### `target`

- **Type:** `Accessor<unknown> | Store<object> | Store<T>`

An accessor, a store, or a store node to mark as pending.

### `key`

- **Type:** `keyof T`

When `target` is a store, the property to mark instead of the whole store.

## Examples

```ts
const send = action(function* (text: string) {
  setState(s => { s.messages.push({ text, status: "sending" }); });
  affects(state.messages.at(-1)!, "status"); // this slot pends until settle
  yield api.send(text);
});

const reload = action(function* () {
  affects(thing);      // the whole store pends…
  refresh(thing);      // …over this otherwise-quiet re-ask
  yield api.done();
});
```

## Caveats

- Marking does not change the value or trigger a refetch; it only reports pending. Pair with `refresh()` to re-ask.

## Common problems

- [The screen looks dead after a click](/guides/debugging-reactivity#the-screen-looks-dead-after-a-click)

## Learn more

- [Mark data as changing: `affects`](/concepts/mutations#mark-data-as-changing-affects)
- [Async reactivity](/concepts/async-reactivity)
- [Avoid unnecessary effects](/guides/avoid-unnecessary-effects)
