#!/usr/bin/env node
/**
 * Tone lint for documentation content.
 *
 * Enforces the mechanical rules from the "AI-assisted writing" section of
 * WRITING.md over src/routes mdx files: no filler, no marketing language,
 * no exclamation marks, none of the sentence shapes that read as generated.
 *
 * Violations in generated reference pages are reported as warnings: the fix
 * belongs in the upstream JSDoc, not in the generated file. Violations in
 * hand-written pages are errors and fail the run. The word "just" is always
 * a warning, because it is often legitimate ("rather than just render").
 */
import fs from "node:fs";
import path from "node:path";

const CONTENT_ROOT = "src/routes";
const GENERATED_MARKER = "Generated by scripts/extract-solid-ref.mjs";

const RULES = [
	{
		name: "filler",
		pattern:
			/\b(actually|basically|obviously|of course|in order to|note that|(?:it is|it's) worth noting|worth noting|keep in mind|there (?:are|is) several options?|this includes)\b/gi,
		severity: "error",
	},
	{
		name: "task-ease",
		pattern: /\b(simply|easy|easily)\b/gi,
		severity: "error",
	},
	{
		name: "hype",
		pattern:
			/\b(powerful|blazing(?:ly)?|seamless(?:ly)?|elegant(?:ly)?|robust|cutting[- ]edge|best[- ]in[- ]class|delightful|magic(?:al)?)\b/gi,
		severity: "error",
	},
	{
		name: "not-x-but-y",
		pattern:
			/\b(?:it'?s not|this is not|not just) [^.\n]{1,60}?, (?:it'?s|but)\b/gi,
		severity: "error",
	},
	{
		name: "exclamation",
		pattern: /[A-Za-z)]!(?=\s|$)/gm,
		severity: "error",
	},
	{
		name: "judgment-word",
		pattern: /\bjust\b/gi,
		severity: "warning",
	},
];

function walk(dir) {
	const files = [];
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const fullPath = path.join(dir, entry.name);
		if (entry.isDirectory()) files.push(...walk(fullPath));
		else if (entry.isFile() && fullPath.endsWith(".mdx")) files.push(fullPath);
	}
	return files;
}

/** Blank out fenced code blocks and inline code, preserving line numbers. */
function stripCode(text) {
	let result = text.replace(/```[\s\S]*?```/g, (block) =>
		block.replace(/[^\n]/g, " ")
	);
	result = result.replace(/`[^`\n]*`/g, (span) => " ".repeat(span.length));
	return result;
}

let errorCount = 0;
let warningCount = 0;

for (const file of walk(CONTENT_ROOT)) {
	const raw = fs.readFileSync(file, "utf8");
	const generated = raw.includes(GENERATED_MARKER);
	const text = stripCode(raw);
	const lines = text.split("\n");

	lines.forEach((line, index) => {
		for (const rule of RULES) {
			rule.pattern.lastIndex = 0;
			let match;
			while ((match = rule.pattern.exec(line)) !== null) {
				const severity =
					generated && rule.severity === "error" ? "warning" : rule.severity;
				const suffix = generated ? " (generated: fix the source JSDoc)" : "";
				console.log(
					`${severity === "error" ? "ERROR" : "warn "} ${file}:${index + 1} [${rule.name}] "${match[0]}"${suffix}`
				);
				if (severity === "error") errorCount++;
				else warningCount++;
			}
		}
	});
}

console.log(`\ntone lint: ${errorCount} error(s), ${warningCount} warning(s)`);
process.exit(errorCount > 0 ? 1 : 0);
