---
title: "Loading"
category: "Components (JSX)"
use_cases: "components (jsx) api, loading usage"
tags:
  - "loading"
  - "components"
  - "jsx"
  - "reference"
  - "api"
  - "v2"
version: "2.0"
description: "Renders a `fallback` while pending async reads inside the subtree settle."
source_repo: "solidjs/solid"
source_ref: "next"
source_path: "packages/solid/src/client/flow.ts"
---

{/* Generated by scripts/extract-solid-ref.mjs. Edit the source JSDoc or disposition map, then regenerate. */}

Renders a `fallback` while pending async reads inside the subtree settle.

Any computation (`createMemo`, `createSignal(fn)`, `createStore(fn)`,
`lazy(...)`, etc.) that throws because data isn't ready is caught by the
nearest enclosing `<Loading>`. The boundary swaps to its `fallback` until
every pending read has resolved, then renders the children.

The optional `on` prop scopes the boundary.
The boundary keeps its previous content for updates caused by writes to other
reactive sources, while `isPending()` reports the pending work.

Scope `<Loading>` around the data-dependent slot, not the surrounding
shell. Wrapping layout chrome (header, nav, footer) in the same boundary
as the data means revalidation replaces the entire screen with the
fallback; rendering chrome outside the boundary keeps it stable while
only the affordance flips.

## Import

```ts
import { Loading } from "solid-js";
```

## Type signature

```ts
function Loading(props: {
  fallback?: JSX.Element;
  on?: any;
  children: JSX.Element;
}): JSX.Element;
```

## Props

### `fallback`

- **Type:** `JSX.Element`
- Optional

Rendered while an async read inside the subtree has no settled value.

### `on`

- **Type:** `any`
- Optional

A value, not an accessor. When it changes and the new content is not ready, the boundary shows its fallback again instead of holding the update.

### `children`

- **Type:** `JSX.Element`

The subtree whose async reads this boundary handles.

## Examples

```tsx
const Profile = lazy(() => import("./Profile"));

<Loading fallback={<Spinner />}>
  <Profile />
</Loading>
```

```tsx
// Only show the fallback for updates caused by writes to `route`.
<Loading fallback={<Skeleton />} on={route}>
  <Page />
</Loading>
```

## Caveats

- The boundary shows its fallback only when a read inside has no settled value yet. Later updates hold the previous content; use `on` for content that should show a placeholder again.
- `on` compares values, not accessors. Pass `on={id()}`, not `on={id}`.
- Place the boundary around the data-dependent slot, not around layout chrome that should stay stable.

## Common problems

- [The screen looks dead after a click](/guides/debugging-reactivity#the-screen-looks-dead-after-a-click)

## Learn more

- [Loading boundaries](/concepts/boundaries#loading-boundaries)
- [Show a placeholder again: `Loading on`](/concepts/async-reactivity#show-a-placeholder-again-loading-on)
- [Components and JSX](/concepts/components-and-jsx)
- [Boundaries](/concepts/boundaries)
