name: Routing Integration Tests
on: push

jobs:
  check-redirects:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: waitFor200
        with:
          site_name: "solid-docs"

      - run: pnpm install

      - name: Ping redirects against deploy url
        id: integration
        run: TEST_URL=${{ steps.waitFor200.outputs.url }} pnpm test:ci
