name: 🔍 Lint / Type Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read
  security-events: read

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install tools & dependencies
        uses: ./.github/actions/install

      - name: TypeScript check
        run: pnpm check:types

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install tools & dependencies
        uses: ./.github/actions/install

      - name: Lint code
        run: pnpm check:lint

      - name: Check formatting
        run: pnpm exec prettier . --check
